spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-ervice
#              uri: http://localhost:8082
              uri:  lb://USERSERVICE
              predicates:
                - Path=/api/users/**

            - id: product-service
#              uri: http://localhost:8081
              uri:  lb://PRODUCTSERVICE
              predicates:
                - Path=/api/products/**

            - id: order-service
#              uri:  http://localhost:8083
              uri:  lb://ORDER-SERVICE
              predicates:
                - Path=/api/cart** , /api/orders/**

            - id: eureka-server
              uri:  http://localhost:8761
              predicates:
                - Path=/eureka/main
              filters:
                - SetPath=/
            - id: eureka-server-static-files
              uri:  http://localhost:8761
              predicates:
                - Path=/eureka/**
  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
