spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
  


server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

       
  
