spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: embarkx
    password: embarkx
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
  

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8083
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

       
  
