spring:
  application:
    name: productservice
  
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
