spring:
  data:
    mongodb:
      database: userdb
      uri: ${MONGO_URL}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 1MB
  file:
    name: logs/${spring.application.name}.log
