spring:
  data:
    mongodb:
      database: userdb
      uri: ${MONGO_URL}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
